class_name ExpansionConstants

const BASE_EXPANSION_WEEK_DURATION: int = 10
const EXPANSION_DURATION_REVIEW_MULTIPLIER: float = 10

# Income
const BASE_EXPANSION_EARNINGS: float = 3000
const EXPANSION_INCOME_FALLOFF_POW_WEEKLY: float = 3
const EXPANSION_INCOME_VARIANCE: float = .2

# Fans
const BASE_EXPANSION_FANS: float = 10
const EXPANSION_FANS_FALLOFF_POW_WEEKLY: float = 3
const EXPANSION_FANS_VARIANCE: float = .2

# Stats
const BASE_DESIGN_POINTS_PER_MECHANIC: float = 10
const BASE_ART_POINTS_PER_MECHANIC: float = 10
const BASE_LORE_POINTS_PER_MECHANIC: float = 10
